# Uso de pandas

**Autor:** Jazna Meza Hidalgo

**Correo Electrónico:** ja.meza@profesor.duoc.cl

**Fecha de Creación:** Diciembre de 2024  
**Versión:** 1.0  

---

## Descripción

Este notebook ofrece un ejemplo del uso de las funcionalidades de pandas

---

## Requisitos de Software

Este notebook fue desarrollado con Python 3.9. A continuación se listan las bibliotecas necesarias:

- pandas (2.2.2)

Para verificar la versión instalada ejecutar usando el siguiente comando, usando la librería de la cual quieres saber la versión:

```bash
import pandas as pd
print(pd.__version__)
````

# Importando librerías

In [3]:
import pandas as pd

# Trabajando con Series

In [4]:
personas = pd.Series(
    ['Carlos', 'Ramiro', 'Pamela', 'Pedro', 'Carolina', 'Xavier', 'Bernarda', 'Hernan', 'Fernanda',
     'Ines', 'Valentina'], index=[1, 11, 4, 3, 7, 9, 10, 2, 5, 6, 8])
print("Amigos: \n%s" % personas)

Amigos:
1        Carlos
11       Ramiro
4        Pamela
3         Pedro
7      Carolina
9        Xavier
10     Bernarda
2        Hernan
5      Fernanda
6          Ines
8     Valentina
dtype: object

In [5]:
# Ahora sin entregar los índices
personas = pd.Series(
    ['Carlos', 'Ramiro', 'Pamela', 'Pedro', 'Carolina', 'Xavier', 'Bernarda', 'Hernan', 'Fernanda',
     'Ines', 'Valentina'])
print("Personas: \n%s" % personas)

Personas:
0        Carlos
1        Ramiro
2        Pamela
3         Pedro
4      Carolina
5        Xavier
6      Bernarda
7        Hernan
8      Fernanda
9          Ines
10    Valentina
dtype: object

In [6]:
# Creando series a través de un diccionario
dictPersonas = {2: 'Carlos', 5: 'Ramiro', 18: 'Pamela', 7: 'Pedro', 6: 'Carolina', 4: 'Xavier', 8: 'Bernarda', 25: 'Hernan',
                33:'Fernanda', 21: 'Ines', 30: 'Valentina'}
personasSerie = pd.Series(dictPersonas)
# Insert new player
personasSerie[10] = 'Cecilia'
print("People through dictionary: \n%s" % personasSerie)

People through dictionary:
2        Carlos
5        Ramiro
18       Pamela
7         Pedro
6      Carolina
4        Xavier
8      Bernarda
25       Hernan
33     Fernanda
21         Ines
30    Valentina
10      Cecilia
dtype: object

# Trabajando con series y describe()

In [7]:
# Serie numérica
s = pd.Series([1, 2, 3])
s.describe()

count    3.0
mean     2.0
std      1.0
min      1.0
25%      1.5
50%      2.0
75%      2.5
max      3.0
dtype: float64

In [8]:
# Serie categorica
s = pd.Series(['a', 'a', 'b', 'c'])
s.describe()

count     4
unique    3
top       a
freq      2
dtype: object

# Trabajando con DataFrame

In [9]:
# Trabajo con dataframe
profesionalesDF = pd.DataFrame(
    {
        'nombre': ['Castillo', 'Ramos', 'Palermo', 'Perez', 'Castro', 'Almendra', 'Baquedano', 'Hernandez',
                 'Pedreros', 'Sepulveda', 'Villa'],
        'profesion': ['Ingeniero', 'Constructor', 'Arquitecto', 'Enfermero', 'Cirujano', 'Dentista',
                        'Sicologo', 'Minero', 'Profesor', 'Piloto', 'Dentista'],
        'ciudad': ['Rancagua', 'Rancagua', 'Punta Arenas', 'Punta Arenas', 'Puerto Varas', 'Rancagua',
                 'Punta Arenas', 'Punta Arenas', 'Punta Arenas', 'Punta Arenas', 'Punta Arenas']
    }, columns=['nombre', 'profesion', 'ciudad'], index=[1, 15, 3, 5, 11, 14, 16, 8, 18, 6, 7]
)
print(profesionalesDF)

       nombre    profesion        ciudad
1    Castillo    Ingeniero      Rancagua
15      Ramos  Constructor      Rancagua
3     Palermo   Arquitecto  Punta Arenas
5       Perez    Enfermero  Punta Arenas
11     Castro     Cirujano  Puerto Varas
14   Almendra     Dentista      Rancagua
16  Baquedano     Sicologo  Punta Arenas
8   Hernandez       Minero  Punta Arenas
18   Pedreros     Profesor  Punta Arenas
6   Sepulveda       Piloto  Punta Arenas
7       Villa     Dentista  Punta Arenas

In [10]:
# Vamos a insertar un nuevo elemento
profesionalesDF.loc[10] = ['Contreras', 'Ingeniero', 'Arica']
# Volvemos a imprimir el dataframe
print(profesionalesDF)

       nombre    profesion        ciudad
1    Castillo    Ingeniero      Rancagua
15      Ramos  Constructor      Rancagua
3     Palermo   Arquitecto  Punta Arenas
5       Perez    Enfermero  Punta Arenas
11     Castro     Cirujano  Puerto Varas
14   Almendra     Dentista      Rancagua
16  Baquedano     Sicologo  Punta Arenas
8   Hernandez       Minero  Punta Arenas
18   Pedreros     Profesor  Punta Arenas
6   Sepulveda       Piloto  Punta Arenas
7       Villa     Dentista  Punta Arenas
10  Contreras    Ingeniero         Arica

In [11]:
profesionalesDF.describe()
# top es el valor más común y freq es la frecuencia del valor más común
# En el caso de top (si hay más de un valor común) como en este ejemplo, entonces la elección es arbitraria

          nombre  profesion        ciudad
count         12         12            12
unique        12         10             4
top     Castillo  Ingeniero  Punta Arenas
freq           1          2             7

In [12]:
# Largo del dataframe
len(profesionalesDF)

12

In [13]:
# Los valores de las dimensiones del DF
profesionalesDF.shape

(12, 3)

In [14]:
# Podemos ver las columnas del dataframe
for profesional in profesionalesDF:
    print(profesional)

nombre
profesion
ciudad

In [15]:
# Muestra los valores de una de las columnas
for profesional in profesionalesDF['nombre']:
    print(profesional)

Castillo
Ramos
Palermo
Perez
Castro
Almendra
Baquedano
Hernandez
Pedreros
Sepulveda
Villa
Contreras

In [16]:
# Muestra solo los valores únicos
for profesional in profesionalesDF['ciudad'].unique():
    print(profesional)

Rancagua
Punta Arenas
Puerto Varas
Arica

In [17]:
# Algunas funciones
print("Max sobre ciudad: %s" %profesionalesDF['ciudad'].max())
print("Min sobre ciudad:", profesionalesDF['ciudad'].min())

Max sobre ciudad: Rancagua
Min sobre ciudad: Arica

# Trabajando con DataFrame con varios tipos de datos en sus columnas

In [18]:
df = pd.DataFrame({'categorical': pd.Categorical(['d','e','f']),
                   'numeric': [1, 2, 3],
                   'object': ['a', 'b', 'c']
                  })
df.describe()

       numeric
count      3.0
mean       2.0
std        1.0
min        1.0
25%        1.5
50%        2.0
75%        2.5
max        3.0

In [19]:
df.describe(include='all')

       categorical  numeric object
count            3      3.0      3
unique           3      NaN      3
top              d      NaN      a
freq             1      NaN      1
mean           NaN      2.0    NaN
std            NaN      1.0    NaN
min            NaN      1.0    NaN
25%            NaN      1.5    NaN
50%            NaN      2.0    NaN
75%            NaN      2.5    NaN
max            NaN      3.0    NaN

# Carga de datos

In [21]:
!wget https://raw.githubusercontent.com/JaznaLaProfe/Mineria_de_datos/master/datos/1.4.4_superstore.csv

--2024-12-24 14:32:53--  https://raw.githubusercontent.com/JaznaLaProfe/Mineria_de_datos/master/datos/1.4.4_superstore.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1573676 (1.5M) [text/plain]
Saving to: ‘1.4.4_superstore.csv’

1.4.4_superstore.cs 100%[===================>]   1.50M  --.-KB/s    in 0.09s

2024-12-24 14:32:54 (17.5 MB/s) - ‘1.4.4_superstore.csv’ saved [1573676/1573676]

In [22]:
# Carga los datos desde el archivo CSV
data = pd.read_csv("1.4.4_superstore.csv")

In [23]:
# Mostrar los 5 primeros registros
data.head()

,Transaction ID,Order ID,Customer ID,Product Name,Sub-Category,Category,Discount,Order Date,Order Day,Order Month,Order Weekday,Order Year,Quantity,Segment,State,Profit CLP,Sales CLP
0,21865-109365-13542,109365,21865,Xerox 22,Paper,Office Supplies,0.0,2016-11-03,3,11,Thursday,2016,3,Consumer,California,7267,15139
1,15745-162026-16405,162026,15745,Xerox 1925,Paper,Office Supplies,0.0,2016-10-08,8,10,Saturday,2016,2,Consumer,California,21713,48251
2,10090-136448-10461,136448,10090,Logitech 910-002974 M325 Wireless Mouse for We...,Accessories,Technology,0.2,2017-09-16,16,9,Saturday,2017,2,Consumer,Pennsylvania,11210,37368
3,16525-142993-23814,142993,16525,"Contico 72""H Heavy-Duty Storage System",Storage,Office Supplies,0.0,2015-10-12,12,10,Monday,2015,2,Consumer,Washington,0,63826
4,15280-115819-4927,115819,15280,PowerGen Dual USB Car Charger,Phones,Technology,0.2,2016-04-19,19,4,Tuesday,2016,5,Consumer,California,10114,31119

In [24]:
data.shape

(9993, 17)

In [25]:
data.columns

Index(['Transaction ID', 'Order ID', 'Customer ID', 'Product Name',
       'Sub-Category', 'Category', 'Discount', 'Order Date', 'Order Day',
       'Order Month', 'Order Weekday', 'Order Year', 'Quantity', 'Segment',
       'State', 'Profit CLP', 'Sales CLP'],
      dtype='object')

In [26]:
data.tail()

,Transaction ID,Order ID,Customer ID,Product Name,Sub-Category,Category,Discount,Order Date,Order Day,Order Month,Order Weekday,Order Year,Quantity,Segment,State,Profit CLP,Sales CLP
9988,13540-132521-3244,132521,13540,Belkin 8 Outlet SurgeMaster II Gold Surge Prot...,Appliances,Office Supplies,0.0,2017-09-23,23,9,Saturday,2017,2,Consumer,Washington,26157,93419
9989,17560-143105-12682,143105,17560,Hewlett Packard 610 Color Digital Copier / Pri...,Copiers,Technology,0.2,2015-12-10,10,12,Thursday,2015,2,Home Office,New York,194684,622988
9990,12250-149811-16023,149811,12250,"GBC Standard Recycled Report Covers, Clear Pla...",Binders,Office Supplies,0.0,2015-01-04,4,1,Sunday,2015,3,Corporate,Minnesota,12089,25185
9991,10300-166800-21126,166800,10300,Hoover Commercial Soft Guard Upright Vacuum An...,Appliances,Office Supplies,0.0,2015-11-19,19,11,Thursday,2015,4,Corporate,Nevada,6535,24204
9992,10720-136322-29264,136322,10720,GBC Personal VeloBind Strips,Binders,Office Supplies,0.7,2016-10-21,21,10,Friday,2016,8,Home Office,Florida,-16420,22391

In [27]:
data.head(8)

,Transaction ID,Order ID,Customer ID,Product Name,Sub-Category,Category,Discount,Order Date,Order Day,Order Month,Order Weekday,Order Year,Quantity,Segment,State,Profit CLP,Sales CLP
0,21865-109365-13542,109365,21865,Xerox 22,Paper,Office Supplies,0.0,2016-11-03,3,11,Thursday,2016,3,Consumer,California,7267,15139
1,15745-162026-16405,162026,15745,Xerox 1925,Paper,Office Supplies,0.0,2016-10-08,8,10,Saturday,2016,2,Consumer,California,21713,48251
2,10090-136448-10461,136448,10090,Logitech 910-002974 M325 Wireless Mouse for We...,Accessories,Technology,0.2,2017-09-16,16,9,Saturday,2017,2,Consumer,Pennsylvania,11210,37368
3,16525-142993-23814,142993,16525,"Contico 72""H Heavy-Duty Storage System",Storage,Office Supplies,0.0,2015-10-12,12,10,Monday,2015,2,Consumer,Washington,0,63826
4,15280-115819-4927,115819,15280,PowerGen Dual USB Car Charger,Phones,Technology,0.2,2016-04-19,19,4,Tuesday,2016,5,Consumer,California,10114,31119
5,12895-152310-25048,152310,12895,Hewlett Packard 310 Color Digital Copier,Copiers,Technology,0.0,2017-08-12,12,8,Saturday,2017,1,Consumer,Washington,70085,233617
6,21790-139304-15141,139304,21790,Acme Office Executive Series Stainless Steel T...,Supplies,Office Supplies,0.0,2017-01-29,29,1,Sunday,2017,1,Consumer,California,1735,6674
7,15250-151750-24566,151750,15250,GBC Instant Report Kit,Binders,Office Supplies,0.8,2017-01-01,1,1,Sunday,2017,5,Consumer,Texas,-7558,5039

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9993 entries, 0 to 9992
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction ID  9993 non-null   object
 1   Order ID        9993 non-null   int64
 2   Customer ID     9993 non-null   int64
 3   Product Name    9993 non-null   object
 4   Sub-Category    9993 non-null   object
 5   Category        9993 non-null   object
 6   Discount        9993 non-null   float64
 7   Order Date      9993 non-null   object
 8   Order Day       9993 non-null   int64
 9   Order Month     9993 non-null   int64
 10  Order Weekday   9993 non-null   object
 11  Order Year      9993 non-null   int64
 12  Quantity        9993 non-null   int64
 13  Segment         9993 non-null   object
 14  State           9993 non-null   object
 15  Profit CLP      9993 non-null   int64
 16  Sales CLP       9993 non-null   int64
dtypes: float64(1), int64(8), object(8)
memory usage: 1.3+ MB

In [29]:
data.describe()

,Order ID,Customer ID,Discount,Order Day,Order Month,Order Year,Quantity,Profit CLP,Sales CLP
count,9993.000000,9993.000000,9993.000000,9993.000000,9993.000000,9993.000000,9993.000000,9.993000e+03,9.993000e+03
mean,134437.893525,16037.562294,0.156188,15.467727,7.810067,2015.722406,3.789753,2.231973e+04,1.789979e+05
std,20252.558140,3429.030030,0.206457,8.748441,3.284598,1.123479,2.225149,1.824389e+05,4.853762e+05
min,100006.000000,10015.000000,0.000000,1.000000,1.000000,2014.000000,1.000000,-5.139733e+06,3.460000e+02
25%,117156.000000,13045.000000,0.000000,8.000000,5.000000,2015.000000,2.000000,1.348000e+03,1.345700e+04
50%,133613.000000,16120.000000,0.200000,15.000000,9.000000,2016.000000,3.000000,6.753000e+03,4.242600e+04
75%,152072.000000,18985.000000,0.200000,23.000000,11.000000,2017.000000,5.000000,2.286700e+04,1.634910e+05
max,169999.000000,21925.000000,0.800000,31.000000,12.000000,2017.000000,14.000000,6.541481e+06,1.762972e+07

In [30]:
data.State

0         California
1         California
2       Pennsylvania
3         Washington
4         California
            ...
9988      Washington
9989        New York
9990       Minnesota
9991          Nevada
9992         Florida
Name: State, Length: 9993, dtype: object

In [31]:
data['State']

0         California
1         California
2       Pennsylvania
3         Washington
4         California
            ...
9988      Washington
9989        New York
9990       Minnesota
9991          Nevada
9992         Florida
Name: State, Length: 9993, dtype: object

In [32]:
data.State.describe()

count           9993
unique            49
top       California
freq            2001
Name: State, dtype: object

In [33]:
data.Discount.describe()

count    9993.000000
mean        0.156188
std         0.206457
min         0.000000
25%         0.000000
50%         0.200000
75%         0.200000
max         0.800000
Name: Discount, dtype: float64

In [34]:
# Filtra las ventas de California
condicion = data['State'] == "California"
condicion

0        True
1        True
2       False
3       False
4        True
        ...
9988    False
9989    False
9990    False
9991    False
9992    False
Name: State, Length: 9993, dtype: bool

In [35]:
data_california = data[condicion]
data_california.head()

,Transaction ID,Order ID,Customer ID,Product Name,Sub-Category,Category,Discount,Order Date,Order Day,Order Month,Order Weekday,Order Year,Quantity,Segment,State,Profit CLP,Sales CLP
0,21865-109365-13542,109365,21865,Xerox 22,Paper,Office Supplies,0.0,2016-11-03,3,11,Thursday,2016,3,Consumer,California,7267,15139
1,15745-162026-16405,162026,15745,Xerox 1925,Paper,Office Supplies,0.0,2016-10-08,8,10,Saturday,2016,2,Consumer,California,21713,48251
4,15280-115819-4927,115819,15280,PowerGen Dual USB Car Charger,Phones,Technology,0.2,2016-04-19,19,4,Tuesday,2016,5,Consumer,California,10114,31119
6,21790-139304-15141,139304,21790,Acme Office Executive Series Stainless Steel T...,Supplies,Office Supplies,0.0,2017-01-29,29,1,Sunday,2017,1,Consumer,California,1735,6674
10,13345-108854-16164,108854,13345,"SAFCO Mobile Desk Side File, Wire Frame",Storage,Office Supplies,0.0,2017-12-08,8,12,Friday,2017,1,Corporate,California,8658,33299

In [36]:
data_california.shape

(2001, 17)

In [37]:
data_california.Discount.describe()

count    2001.000000
mean        0.072764
std         0.095225
min         0.000000
25%         0.000000
50%         0.000000
75%         0.200000
max         0.200000
Name: Discount, dtype: float64

In [38]:
nombre_columnas = data.columns
cumple_condicion = lambda columna: columna.startswith("Order") or columna.startswith("ORDER") or columna.startswith('order')
comienza_con_order = [columna for columna in nombre_columnas if cumple_condicion(columna)]
data_order = data[comienza_con_order]
data_order.head()

   Order ID  Order Date  Order Day  Order Month Order Weekday  Order Year
0    109365  2016-11-03          3           11      Thursday        2016
1    162026  2016-10-08          8           10      Saturday        2016
2    136448  2017-09-16         16            9      Saturday        2017
3    142993  2015-10-12         12           10        Monday        2015
4    115819  2016-04-19         19            4       Tuesday        2016

In [39]:
comienza_con_order

['Order ID',
 'Order Date',
 'Order Day',
 'Order Month',
 'Order Weekday',
 'Order Year']

In [40]:
cumple_condicion

In [41]:
subset = data[['Order Month', 'Profit CLP', 'Sales CLP', 'Discount', 'Quantity']]
matriz_corr = subset.corr()
matriz_corr

             Order Month  Profit CLP  Sales CLP  Discount  Quantity
Order Month     1.000000   -0.000522  -0.000615 -0.004855  0.023264
Profit CLP     -0.000522    1.000000   0.479067 -0.219481  0.066241
Sales CLP      -0.000615    0.479067   1.000000 -0.028197  0.200808
Discount       -0.004855   -0.219481  -0.028197  1.000000  0.008680
Quantity        0.023264    0.066241   0.200808  0.008680  1.000000